# =========================================
#           Abstract Cooldown
#
# Связаться с автором - AbstractCoder.ru
# =========================================

# Использовать ли Vault? У вас должен быть установлен плагин Vault.
# Это необходимо для настройки разного кулдауна для разных донат-групп.
# Если Вам это не нужно, то можете отключить
useVault: true

# Настройка приоритетов донат-групп по убыванию (сначала более важные группы).
# Это позволит Вам не дублировать одинаковое время для последующих групп,
# так акк плагин будет учитывать прироритет.
# Например, для команды ban не указана задержка для группы admin,
# так что у группы admin задержка будет такая же, как и для ultra.
#
# Если вы не используйте Vault, то можете смело удалить эту секцию
groupPriorities:
  - admin
  - helper
  - help
  - elite
  - vip

# Команды для которых действует кулдаун
commands:
  # Команда или любой из его алиасов.
  ban:
    # Если установлено true, то плагин автоматически проверяет
    # алиасы (заменители) этой команды для наложения кулдауна.
    # Можно убрать и будет работать.
    checkAliases: true
    # Здесь можно указать список команд, кулдаун для которых будет общим с этой командой.
    # В данном примере, кулдаун для /ban и /tempban будет общим.
    # Это также можно использовать для выслеживания алиасов команды, которых нет в plugin.yml
    # Можно убрать и будет работать.
    similarCommands: [tempban]
    # Право, которое должно быть у игрока, чтобы кулдаун сработал.
    # Тем самым, если игрок и так не может использовать команду, то кулдаун не будет наложен.
    # Можно убрать и будет работать.
    permission: 'essentials.ban'
    # Минимальное количество аргументов, для того чтобы кулдаун сработал.
    # Можно убрать и будет работать.
    minArgsLength: 2
    # Кастомное сообщение для команды, если игрок использует ее во время кулдауна.
    # Можно использовать плейсхолдер {time} для указания оставшегося времени.
    # Можно убрать и будет отправляться дефолтное сообщение из language.yml
    customMessage: '&cНельзя банить так часто! Подожди еще &a{time}'
    # Стандартное время кулдауна. Можно использовать d (дни), h (часы), m (минуты), s (секунды).
    # В данном примере время - два с половиной часа.
    defaultTime: 2h 30m
    # Время кулдауна для определенных групп. Для работы нужен плагин Vault и useVault: true
    # Время указывать в таком же формате. Дублировать одно и то же время для последующих групп не надо,
    # если вы установили приоритеты в начале конфига, то плагин автоматически будет их учитывать.
    groupsTime:
      elite: 2h
      ultra: 1h
  fix:
    checkAliases: true
    permission: 'essentials.repair'
    defaultTime: 1m
  # Плагин также позволяет указывать нужные аргументы для команд.
  # Кулдауны для /fix и /fix all разные (1 минута и 5 минут).
  # Это позволяет гибко настраивать кулдаун для некоторых команд.
  # Обязательно заключайте подобные команды в одинарные кавычки, пример 'fix all'
  'fix all':
    checkAliases: true
    permission: 'essentials.repair.all'
    defaultTime: 5m